spring:
  application:
    name: microservice-rooms
  profiles:
    active: default
  config:
    import: optional:configserver:https://config-server-d5ar.onrender.com/
file:
  upload-dir: uploads/rooms
