services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
      args:
        MODULE: config-server
    environment:
      - PORT=8888
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    image: italomoroco/hotel-config-server
  eureka:
    build:
      context: .
      dockerfile: microservice-eureka/Dockerfile
      args:
        MODULE: microservice-eureka
    environment:
      - PORT=8761
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: italomoroco/hotel-eureka
  gateway:
    build:
      context: .
      dockerfile: microservice-gateway/Dockerfile
      args:
        MODULE: microservice-gateway
    depends_on:
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - PORT=8090
      - SPRING_DATASOURCE_FRONT_PROD=${URL_FRONT_PROD}
      - SPRING_DATASOURCE_FRONT_DEV=${URL_FRONT_DEV}
    ports:
      - "8090:8090"
    image: italomoroco/hotel-gateway
  #Modules
  promotions:
    build:
      context: .
      dockerfile: microservice-promotions/Dockerfile
      args:
        MODULE: microservice-promotions
    depends_on:
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - PORT=0
      - SPRING_DATASOURCE_URL=${DB_HOST_POSTGRES}/${DB_PROMOTIONS_ROOMS}
      - SPRING_DATASOURCE_USER=${DB_USERNAME_POSTGRES}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD_POSTGRES}
      - SPRING_DATASOURCE_CONFIG-SERVER=${URL_CONFIG_SERVER}
      - SPRING_DATASOURCE_EUREKA=${URL_EUREKA}
    env_file:
      - .env
    image: italomoroco/hotel-promotions
  bookings:
    build:
      context: .
      dockerfile: microservice-bookings/Dockerfile
      args:
        MODULE: microservice-bookings
    depends_on:
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - PORT=0
      - SPRING_DATASOURCE_URL=${DB_HOST_POSTGRES}/${DB_BOOKINGS}
      - SPRING_DATASOURCE_USER=${DB_USERNAME_POSTGRES}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD_POSTGRES}
      - SPRING_DATASOURCE_CONFIG-SERVER=${URL_CONFIG_SERVER}
      - SPRING_DATASOURCE_EUREKA=${URL_EUREKA}
    env_file:
      - .env
    image: italomoroco/hotel-bookings
  users:
    build:
      context: .
      dockerfile: microservice-users/Dockerfile
      args:
        MODULE: microservice-users
    depends_on:
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - PORT=0
      - SPRING_DATASOURCE_URL=${DB_HOST_POSTGRES}/${DB_USERS}
      - SPRING_DATASOURCE_USER=${DB_USERNAME_POSTGRES}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD_POSTGRES}
      - SPRING_DATASOURCE_CONFIG-SERVER=${URL_CONFIG_SERVER}
      - SPRING_DATASOURCE_EUREKA=${URL_EUREKA}
    env_file:
      - .env
    image: italomoroco/hotel-users
  rooms:
    build:
      context: .
      dockerfile: microservice-rooms/Dockerfile
      args:
        MODULE: microservice-rooms
    depends_on:
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - PORT=0
      - SPRING_DATASOURCE_URL=${DB_HOST_POSTGRES}/${DB_PROMOTIONS_ROOMS}
      - SPRING_DATASOURCE_USER=${DB_USERNAME_POSTGRES}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD_POSTGRES}
      - SPRING_DATASOURCE_CONFIG-SERVER=${URL_CONFIG_SERVER}
      - SPRING_DATASOURCE_EUREKA=${URL_EUREKA}
    env_file:
      - .env
    image: italomoroco/hotel-rooms
  messages:
    build:
      context: .
      dockerfile: microservice-message/Dockerfile
      args:
        MODULE: microservice-message
    depends_on:
      eureka:
        condition: service_healthy
      #config-server:
        #condition: service_healthy
    environment:
      - PORT=0
      - SPRING_DATASOURCE_URL=${DB_HOST_MYSQL}/${DB_MESSAGES}
      - SPRING_DATASOURCE_USER=${DB_USERNAME_MYSQL}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD_MYSQL}
      - SPRING_DATASOURCE_CONFIG-SERVER=${URL_CONFIG_SERVER}
      - SPRING_DATASOURCE_EUREKA=${URL_EUREKA}
    env_file:
      - .env
    image: italomoroco/hotel-messages