services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
      args:
        MODULE: config-server
    environment:
      - PORT=8888
    ports:
      - "8888:8888"

  eureka:
    build:
      context: .
      dockerfile: microservice-eureka/Dockerfile
      args:
        MODULE: microservice-eureka
    environment:
      - PORT=8761
    ports:
      - "8761:8761"

  gateway:
    build:
      context: .
      dockerfile: microservice-gateway/Dockerfile
      args:
        MODULE: microservice-gateway
    depends_on:
      - eureka
      - config-server
    environment:
      - PORT=8090
    ports:
      - "8090:8090"
#Modules
  promotions:
    build:
      context: .
      dockerfile: microservice-promotions/Dockerfile
      args:
        MODULE: microservice-promotions
    depends_on:
      - eureka
      - config-server
    environment:
      - PORT=0

  bookings:
    build:
      context: .
      dockerfile: microservice-bookings/Dockerfile
      args:
        MODULE: microservice-bookings
    depends_on:
      - eureka
      - config-server
    environment:
      - PORT=0
  users:
    build:
      context: .
      dockerfile: microservice-users/Dockerfile
      args:
        MODULE: microservice-users
    depends_on:
      - eureka
      - config-server
    environment:
      - PORT=0
  rooms:
    build:
      context: .
      dockerfile: microservice-rooms/Dockerfile
      args:
        MODULE: microservice-rooms
    depends_on:
      - eureka
      - config-server
    environment:
      - PORT=0
  messages:
    build:
      context: .
      dockerfile: microservice-message/Dockerfile
      args:
        MODULE: microservice-message
    depends_on:
      - eureka
      - config-server
    environment:
      - PORT=0
