server:
  port: 9093
spring:
  output:
    ansi:
      enabled: always
  application:
    name: microservice-rooms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_system_hotel
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    #This line is used for testing.
    #enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka

