server:
  port: 8090

spring:
  application:
    name: microservice-gateway

  config:
    import: optional:configserver:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
