server:
  port: ${PORT:0}
spring:
  output:
    ansi:
      enabled: always
  application:
    name: microservice-promotions
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: microservice-eureka
  client:
    #This line is used for testing.
    #enabled: false
    enabled: true
    service-url:
      defaultZone: https://hotel-eureka-v1-0.onrender.com/eureka/