server:
  port: 9091
spring:
  output:
    ansi:
      enabled: always
  application:
    name: microservice-promotions
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/msvc-promotions
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    #This line is used for testing.
    #enabled: false
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka