server:
  port: 8761

spring:
  application:
    name: micro-eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: microservice-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://microservice-eureka:${server.port}/eureka/