server:
  port: ${PORT:0}
spring:
  output:
    ansi:
      enabled: always
  application:
    name: microservice-promotions
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST_POSTGRES_PROMOTION_ROOMS}
    username: ${DB_USERNAME_POSTGRES}
    password: ${DB_PASSWORD_POSTGRES}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: microservice-promotions-ucmr.onrender.com
    #hostname: microservice-promotions
    #prefer-ip-address: false
    prefer-ip-address: true
   # secure-port: 443
    secure-port-enabled: false
    #instance:
    #  instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.value}"
    #metadata-map:
    #  instance: ${spring.application.name}:${random.value}
  client:
    #This line is used for testing.
    #enabled: false
    enabled: true
    service-url:
      #defaultZone: https://microservice-eureka-mmco.onrender.com/eureka/
      defaultZone: ${EUREKA_URL}/eureka/