spring:
  cloud:
    gateway:
      # 1) Configuración global de CORS
      globalcors:
        corsConfigurations:
          '[/**]':             # Aplica a todas las rutas del Gateway
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      # 2) Tus rutas existentes
      routes:
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: microservice-bookings
          uri: lb://microservice-bookings
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=2
