spring:
  cloud:
    gateway:
      routes:
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: microservice-bookings
          uri: lb://microservice-bookings
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=2
