oauth:
  warmup-url: ${OAUTH_URL}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_URL}/.well-known/jwks.json
          issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - https://fronted-hotel-vercel-prod.vercel.app
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: microservice-users
          uri: lb://microservice-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: microservice-bookings
          uri: lb://microservice-bookings
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=2
        - id: microservice-promotions
          uri: lb://microservice-promotions
          predicates:
            - Path=/api/promotions/**
          filters:
            - StripPrefix=2
        - id: microservice-rooms
          uri: lb://microservice-rooms
          predicates:
            - Path=/api/rooms/**
          filters:
            - StripPrefix=1
        - id: microservice-oauth
          uri: lb://microservice-oauth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 1
                statuses: BAD_GATEWAY, INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                methods: POST
                backoff:
                  firstBackoff: 200ms
                  maxBackoff: 1s
                  factor: 2
        - id: microservice-roomtype
          uri: lb://microservice-rooms
          predicates:
            - Path=/api/roomtype/**
          filters:
            - StripPrefix=1
        - id: microservice-tags
          uri: lb://microservice-rooms
          predicates:
            - Path=/api/tags/**
          filters:
            - StripPrefix=1
        - id: microservice-message
          uri: lb://microservice-message
          predicates:
            - Path=/api/messages/**
          filters:
            - StripPrefix=2