server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
      - id: promotions
        uri: http://localhost:9091
        predicates:
          - Path=/api/promotion/**
